// ans.cpp 5 Aug 17, 19:26:50 85.41 0.04 Judging completed in 10.065s on AWS Oregon.
%:include<iostream>
int
n;
int
i;
int
a;
int
s;
int
c;
int
u;
main()<%
u++;
c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++;c++; 
std::cin>>n;
for(;i<n;i++)<%
for(;a<i;a++)<%
a++;
std::cout<<a<<(char)c;
a--;
%>
for(;(a);a--);
i++;
std::cout<<i<<std::endl;
i--;
%>
%>